config/routes.rb
Hddreport::Application.routes.draw do
  
  

  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do 

  root 'welcome#index'
  resources :devices

  post "hddbenchmark/upload"
  get "hddbenchmark/:id/results" => 'hddbenchmark#results'
  get "hddbenchmark/:id/min" => 'hddbenchmark#min'
  get "hddbenchmark/:id/avg" => 'hddbenchmark#avg'
  get "hddbenchmark/:id/jumps" => 'hddbenchmark#jumps'
  resources :hddbenchmark

  end
end

app/models/add_properties_to_hddbenchmark.rb
class AddPropertiesToHddbenchmark < ActiveRecord::Base
end

app/models/device.rb
class Device < ActiveRecord::Base
	has_many :hddbenchmarks
end

app/models/hddbenchmark.rb
class Hddbenchmark < ActiveRecord::Base
	has_many :measurements
	belongs_to :device
	def iterations
		self.measurements.size()
	end
	def reduction_parameter
		(self.iterations/1000).round(0)
	end

	def reduced_measurements
		self.measurements.exclude_max_mins.reduce(self.reduction_parameter)
	end

	def mins
		self.measurements.exclude_max_mins.min(1000)	
	end
	def avg
		self.measurements.exclude_max_mins.avg(1000)	
	end
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	belongs_to :hddbenchmark

	scope :reduce, lambda{ |ratio| where("iteration % ? = ?", ratio, 0).select("iteration, laptime") }
	scope :reduce_from_to, lambda{ |from, to| where("iteration % ? = ? AND iteration >= ? AND iteration <= ?", ((to-from)/1000).round(0)+1, 0, from, to).select("iteration, laptime") }

	scope :from_to, lambda{ |from, to| where("iteration >= ? AND iteration <= ?", from, to).select("iteration, laptime, id") }
	scope :exclude_max_mins, lambda {joins(:hddbenchmark).where("laptime >= hddbenchmarks.min_measured_value AND laptime <= hddbenchmarks.max_measured_value")}

	scope :avg, lambda { |range| group(" cast(iteration / 1000 as int)").select("avg(laptime) as laptime, iteration") }
	scope :min, lambda { |range| group(" cast(iteration / 1000 as int)").select("min(laptime) as laptime, iteration") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :computer, :address)
    end
end

app/controllers/hddbenchmark_controller.rb
class HddbenchmarkController < ApplicationController
  before_action :set_hddbenchmark, only: [:show, :edit, :update, :destroy, :avg, :results, :min, :jumps]
  skip_before_filter :verify_authenticity_token
  def upload
  	data = params[:data]
  	theBenchmark = Hddbenchmark.create(
      :name => params[:testName],
      :hd_geometry_heads => params[:properties]["hd_geometry.heads"],
      :hd_geometry_sectors => params[:properties]["hd_geometry.sectors"],
      :hd_geometry_start => params[:properties]["hd_geometry.start"],
      :hd_geometry_cylinders => params[:properties]["hd_geometry.cylinders"],


      :HDIO_GET_UNMASKINTR => params[:properties]["HDIO_GET_UNMASKINTR"],
      :HDIO_GET_MULTCOUNT => params[:properties]["HDIO_GET_MULTCOUNT"],
      :HDIO_GET_KEEPSETTINGS => params[:properties]["HDIO_GET_KEEPSETTINGS"],
      :HDIO_GET_32BIT => params[:properties]["HDIO_GET_32BIT"],
      :HDIO_GET_NOWERR => params[:properties]["HDIO_GET_NOWERR"],
      :HDIO_GET_DMA => params[:properties]["HDIO_GET_DMA"],
      :HDIO_GET_NICE => params[:properties]["HDIO_GET_NICE"],
      :HDIO_GET_WCACHE => params[:properties]["HDIO_GET_WCACHE"],
      :HDIO_GET_ACOUSTIC => params[:properties]["HDIO_GET_ACOUSTIC"],
      :HDIO_GET_ADDRESS => params[:properties]["HDIO_GET_ADDRESS"],
      :HDIO_GET_BUSSTATE => params[:properties]["HDIO_GET_BUSSTATE"],
      :properties => params[:modePages].to_json
    )

  	measurements = []
  	data.each_with_index do |d, i|
  		measurements << Measurement.new(:laptime => d, :hddbenchmark_id => theBenchmark.id, :iteration => i)
  	  if measurements.size() > 1000
        Measurement.import measurements
        measurements = []
      end
    end
  	

	#puts data
    respond_to do |format|
  	  format.json{ render :json => "hello"}
	  end
  end

  def results
    @benchmark = Hddbenchmark.find(params[:id])
    if params[:from] == nil
      data = @benchmark.reduced_measurements
    else
      data = @benchmark.measurements.exclude_max_mins.reduce_from_to(params[:from].to_i, params[:to].to_i)
    end
    @result = []
    data.each do |d|
      @result << [d.iteration, d.laptime]
    end
    
    respond_to do |format|
      format.html
      format.json{ render :json => @result}
    end
  end

  def min
    data = @benchmark.mins
    
    @result = []
    data.each do |d|
      @result << [d.iteration, d.laptime]
    end

    respond_to do |format|
      format.html
      format.json{ render :json => @result}
    end
  end

  def avg
    data = @benchmark.avg
    
    @result = []
    data.each do |d|
      @result << [d.iteration, d.laptime]
    end

    respond_to do |format|
      format.html
      format.json{ render :json => @result}
    end
  end


  def jumps
    data = @benchmark.avg
    oldvalue = 0
    oldvalue2 = 0
    @result = []

    data.each do |d|
      oldvalue2 = oldvalue
      oldvalue = d.laptime
      if (oldvalue2 - d.laptime).abs > @benchmark.zone_var
        @result << [d.iteration, d.laptime]
      end
    end


    respond_to do |format|
      format.html
      format.json{ render :json => @result}
    end
  end


  # PATCH/PUT /hddbenchmarks/1
  # PATCH/PUT /hddbenchmarks/1.json
  def update
    respond_to do |format|
      puts hddbenchmark_params
      if @benchmark.update(hddbenchmark_params)
        format.html { redirect_to @benchmark, notice: 'Hddbenchmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @benchmark.errors, status: :unprocessable_entity }
      end
    end
  end

  

  def index
  	
  	@benchmarks = Hddbenchmark.all
  end

  def show
  	#@benchmark = Hddbenchmark.find(params[:id])
    begin
      @properties = JSON.parse(@benchmark.properties)
      @properties = @properties.enum_for(:each_slice, 20).to_a
    rescue
      @properties = nil
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hddbenchmark
      @benchmark = Hddbenchmark.find(params[:id])
    end
    def hddbenchmark_params
      params.require(:hddbenchmark).permit(:name, :max_measured_value, :min_measured_value, :device_id, :zone_var)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/hddbenchmark_helper.rb
module HddbenchmarkHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :computer %><br>
    <%= f.text_field :computer %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table class="table">
  <thead>
    <tr>
      <th>Action</th>
      <th>Name</th>
      <th>Computer</th>
      <th>Address</th>
      <th>Benchmarks</th>

    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td>
          <div class="btn-group btn-group-xs">
            <%= link_to 'Show', device, :class => "btn btn-default" %>
            <!--<%= link_to 'Edit', edit_device_path(device), :class => "btn btn-default" %>
            <%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>-->
          </div>
        </td>
        <td><%= link_to device.name, device %></td>
        <td><%= device.computer %></td>
        <td><%= device.address %></td>
        <td><%= device.hddbenchmarks.count %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path, :class => "btn btn-primary btn-lg" %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @device.name %></h1>
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">Meta Data</div>
			<div class="panel-body">
				<p>
				  <strong>Computer:</strong>
				  <%= @device.computer %>
				</p>

				<p>
				  <strong>Address:</strong>
				  <%= @device.address %>
				</p>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">Benchmarks</div>
			<div class="panel-body">
				<ul class="list-group">
					<% @device.hddbenchmarks.each do |benchmark| %>
					<li class="list-group-item">
						<h3><%= link_to benchmark.name, benchmark %></h3>
						<%= benchmark.created_at%>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>



<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/hddbenchmark/_form.html.erb
<%= form_for(@benchmark) do |f| %>

  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :min_measured_value %><br>
    <%= f.text_field :min_measured_value, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :max_measured_value %><br>
    <%= f.text_field :max_measured_value, :class => "form-control" %>
  </div>
    
  <div class="form-group">
    <%= f.label :device_id %><br>
    <%= f.collection_select(:device_id , Device.all, :id, :name, {}, {:class=> "form-control"})  %>
  </div>

  <div class="form-group">
    <%= f.label :zone_var %><br>
    <%= f.text_field :zone_var, :class => "form-control" %>
  </div>

  
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/hddbenchmark/edit.html.erb
<h1>Edit: <%= @benchmark.name %></h1>

<%= render 'form', :html => {:role => "form"} %>

app/views/hddbenchmark/index.html.erb
<h1>Hddbenchmarks</h1>
<ul class="list-group">
<% @benchmarks.each do |benchmark| %>
	<li class="list-group-item">
	<h3><%= link_to benchmark.name, benchmark %></h3> <%= benchmark.created_at%>
	<span class="badge"><%=benchmark.device_id %></span>
	</li>
<% end %>
</ul>

app/views/hddbenchmark/min.html.erb
<%= @result.to_json %>

app/views/hddbenchmark/results.html.erb
<%= @result.to_json %>

app/views/hddbenchmark/show.html.erb
<div class="page-header">
<h1><%= @benchmark.name %></h1>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">Meta Data</div>
			<div class="panel-body">
				<dl class="dl-horizontal">
				  <dt>hd_geometry_heads</dt>
				  <dd><%= @benchmark.hd_geometry_heads %></dd>

				  <dt>hd_geometry_sectors</dt>
				  <dd><%= @benchmark.hd_geometry_sectors %></dd>

				  <dt>hd_geometry_start</dt>
				  <dd><%= @benchmark.hd_geometry_start %></dd>

				  <dt>hd_geometry_cylinders</dt>
				  <dd><%= @benchmark.hd_geometry_cylinders %></dd>

				  <dt>HDIO_GET_UNMASKINTR</dt>
				  <dd><%= @benchmark.HDIO_GET_UNMASKINTR %></dd>

				  <dt>HDIO_GET_MULTCOUNT</dt>
				  <dd><%= @benchmark.HDIO_GET_MULTCOUNT %></dd>

				  <dt>HDIO_GET_KEEPSETTINGS</dt>
				  <dd><%= @benchmark.HDIO_GET_KEEPSETTINGS %></dd>

				  <dt>HDIO_GET_32BIT</dt>
				  <dd><%= @benchmark.HDIO_GET_32BIT %></dd>

				  <dt>HDIO_GET_NOWERR</dt>
				  <dd><%= @benchmark.HDIO_GET_NOWERR %></dd>

				  <dt>HDIO_GET_DMA</dt>
				  <dd><%= @benchmark.HDIO_GET_DMA %></dd>

				  <dt>HDIO_GET_NICE</dt>
				  <dd><%= @benchmark.HDIO_GET_NICE %></dd>

				  <dt>HDIO_GET_WCACHE</dt>
				  <dd><%= @benchmark.HDIO_GET_WCACHE %></dd>

				  <dt>HDIO_GET_ACOUSTIC</dt>
				  <dd><%= @benchmark.HDIO_GET_ACOUSTIC %></dd>

				  <dt>HDIO_GET_ADDRESS</dt>
				  <dd><%= @benchmark.HDIO_GET_ADDRESS %></dd>

				  <dt>HDIO_GET_BUSSTATE</dt>
				  <dd><%= @benchmark.HDIO_GET_BUSSTATE %></dd>
				</dl>
			</div>
			</div>
			<div class="panel panel-default">
			<div class="panel-heading">Meta Data 2</div>
			<div class="panel-body">
				<div class="row">
					<% if !@properties.blank? %>
					  <% for itemSplits in @properties %>
					  	<div class="col-md-6">
					  		<dl class="dl-horizontal">
					  		<% if !itemSplits.blank? %>
					  		  <% for item in itemSplits %>
					  		    <dt><%= item.first %></dt>
					  		    <dd><%= item.second %></dd>
					  		  <% end %>
					  		<% else %>
					  		  
					  		<% end %>
					  		</dl>
					  	</div>  
					  <% end %>
					<% else %>
					  
					<% end %>
				</div>
			</div>
		</div>
	</div>

</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<div id="container" style="height:400px"></div>
			</div>
		</div>
	</div>

</div>
<%= link_to 'Edit', edit_hddbenchmark_path(@benchmark), :class => "btn btn-default" %>

app/views/hddbenchmark/upload.html.erb
<h1>Hddbenchmark#upload</h1>
<p>Find me in app/views/hddbenchmark/upload.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hddreport</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %> 
  <script src="http://code.highcharts.com/stock/highstock.src.js"></script>
  <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


</head>
<body>
<div class="container">

	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				 <a class="navbar-brand" href="/hdd">HDD Report <%= ENV['RAILS_ENV'] %></a>
			</div>
      <ul class="nav navbar-nav">
        <li><a href="/hdd/devices">Devices</a></li>
        <li><a href="/hdd/hddbenchmark">Benchmarks</a></li>
      </ul>
		</div>
	</nav>
<%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Benchmarking <small>Hard Disk Drives</small></h1>
  <p></p>
  <p><a class="btn btn-primary btn-lg" href="/hdd/devices" role="button">Select devices</a></p>
</div>

<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">Github C++</div>
			<div class="panel-body">
				<ul class="list-unstyled">
					<li>
						<a href="https://github.com/cdeckert/Team-Project-HDD-Benchmarks">C++ Repo</a>
					</li>
					<li>
						<a href="https://github.com/cdeckert/Team-Project-HDD-Benchmarks/issues/milestones">Milestones</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">Github Rails</div>
			<div class="panel-body">
				<ul class="list-unstyled">
					<li>
						<a href="https://github.com/cdeckert/HDDReport">Rails Repo</a>
					</li>
					
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-4">
	</div>
</div>